// <auto-generated />
using System;
using LeadEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeadEngineDbContext))]
    [Migration("20260724215939_AddGoogleAdsControlledPublishing")]
    partial class AddGoogleAdsControlledPublishing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LeadEngine.Domain.Entities.Campanha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BeneficiosJson")
                        .HasColumnType("json");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDespublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataGeracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricoesAnunciosJson")
                        .HasColumnType("json");

                    b.Property<long?>("DuracaoGeracaoMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErroGeracao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("MensagemWhatsApp")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ModeloIa")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Operadora")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("OrcamentoDiario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PalavrasChaveJson")
                        .HasColumnType("json");

                    b.Property<string>("PalavrasChaveNegativasJson")
                        .HasColumnType("json");

                    b.Property<string>("PerguntasFrequentesJson")
                        .HasColumnType("json");

                    b.Property<string>("ProviderIa")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("Publicada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Regiao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubtituloLandingPage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("TextoBotao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("TipoPublico")
                        .HasColumnType("int");

                    b.Property<string>("TituloLandingPage")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("TitulosAnunciosJson")
                        .HasColumnType("json");

                    b.Property<string>("UrlPublica")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Publicada", "Ativo");

                    b.ToTable("Campanhas", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.CampanhaRevisao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CampanhaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConteudoAnterior")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("ConteudoNovo")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstrucaoAdicional")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ModeloIa")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<string>("ProviderIa")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("Secao")
                        .HasColumnType("int");

                    b.Property<string>("TipoAlteracao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("DataAlteracao");

                    b.ToTable("CampanhasRevisoes", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Sensivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Valor")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ValorProtegido")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("ConfiguracoesSistema", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.ConfiguracaoSistemaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("ConfiguracaoSistemaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrigemAlteracao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("Sensivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ValorNovo")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Chave");

                    b.HasIndex("ConfiguracaoSistemaId");

                    b.HasIndex("DataAlteracao");

                    b.ToTable("ConfiguracoesSistemaHistorico", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsConta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AccessTokenExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AccessTokenProtegido")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataConexao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<bool>("Padrao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshTokenProtegido")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("Padrao");

                    b.ToTable("GoogleAdsContas", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsPlanoPublicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvisosValidacaoJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<Guid>("CampanhaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoMoeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("ConteudoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrosValidacaoJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<Guid>("GoogleAdsContaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeCampanha")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("OrcamentoDiario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PayloadPreviewJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TipoRede")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UrlFinal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId")
                        .IsUnique();

                    b.HasIndex("GoogleAdsContaId");

                    b.HasIndex("Status");

                    b.ToTable("GoogleAdsPlanosPublicacao", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsPublicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CampanhaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ConfirmationExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConfirmationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicioPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPreparacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataValidacaoRemota")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErroCodigo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ErroMensagemControlada")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ErrosJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("GeoTargetResourceName")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("GoogleAdsContaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GoogleAdsPlanoPublicacaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("LanguageResourceName")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("PreviewHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PreviewVersao")
                        .HasColumnType("int");

                    b.Property<string>("RecursosJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("RequestIdPublicacao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("RequestIdValidacao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<bool>("Teste")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("GoogleAdsContaId");

                    b.HasIndex("Status");

                    b.HasIndex("GoogleAdsPlanoPublicacaoId", "PreviewVersao", "PreviewHash")
                        .IsUnique();

                    b.ToTable("GoogleAdsPublicacoes", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsRecursoPublicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("GoogleAdsPublicacaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleAdsPublicacaoId");

                    b.HasIndex("ResourceName");

                    b.ToTable("GoogleAdsRecursosPublicados", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CampanhaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CnpjNormalizado")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<bool>("ConsentimentoContato")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ConsentimentoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("EmailNormalizado")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErroEnvio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Fbclid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Gclid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("HospitalDesejado")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("IdadesJson")
                        .HasColumnType("json");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("OperadoraDesejada")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("OrigemCaptura")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PlanoAtual")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool?>("PossuiPlanoAtual")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("QuantidadeFuncionarios")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeVidas")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusEnvioExterno")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("TentativasEnvioExterno")
                        .HasColumnType("int");

                    b.Property<string>("TextoConsentimentoVersao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoContratacao")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UltimoErroEnvioExterno")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UltimoStatusHttpIntegracao")
                        .HasColumnType("int");

                    b.Property<string>("UserAgentResumo")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("WhatsAppNormalizado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.HasIndex("WhatsAppNormalizado");

                    b.HasIndex("CampanhaId", "WhatsAppNormalizado", "CriadoEm");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.LogIntegracaoLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("StatusHttp")
                        .HasColumnType("int");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("LeadId");

                    b.ToTable("LogsIntegracaoLead", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.OrigemLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdGroupId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("AdId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CampaignId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Device")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Gbraid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Gclid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Keyword")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("LandingPage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MatchType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Wbraid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("Gclid");

                    b.HasIndex("LandingPage");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.HasIndex("UtmCampaign");

                    b.ToTable("OrigensLead", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.TentativaCapturaLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Duplicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gclid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("LandingPage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("WhatsAppNormalizado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("LeadId");

                    b.HasIndex("WhatsAppNormalizado");

                    b.ToTable("TentativasCapturaLead", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.CampanhaRevisao", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Campanha", "Campanha")
                        .WithMany("Revisoes")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.ConfiguracaoSistemaHistorico", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.ConfiguracaoSistema", "ConfiguracaoSistema")
                        .WithMany("Historico")
                        .HasForeignKey("ConfiguracaoSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracaoSistema");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsPlanoPublicacao", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadEngine.Domain.Entities.GoogleAdsConta", "GoogleAdsConta")
                        .WithMany()
                        .HasForeignKey("GoogleAdsContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("GoogleAdsConta");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsPublicacao", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadEngine.Domain.Entities.GoogleAdsConta", "GoogleAdsConta")
                        .WithMany()
                        .HasForeignKey("GoogleAdsContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadEngine.Domain.Entities.GoogleAdsPlanoPublicacao", "PlanoPublicacao")
                        .WithMany()
                        .HasForeignKey("GoogleAdsPlanoPublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("GoogleAdsConta");

                    b.Navigation("PlanoPublicacao");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsRecursoPublicado", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.GoogleAdsPublicacao", "Publicacao")
                        .WithMany("Recursos")
                        .HasForeignKey("GoogleAdsPublicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacao");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.Lead", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Campanha", "Campanha")
                        .WithMany("Leads")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.LogIntegracaoLead", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Lead", "Lead")
                        .WithMany("LogsIntegracao")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.OrigemLead", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Lead", "Lead")
                        .WithOne("Origem")
                        .HasForeignKey("LeadEngine.Domain.Entities.OrigemLead", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.TentativaCapturaLead", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.Campanha", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Revisoes");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.ConfiguracaoSistema", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.GoogleAdsPublicacao", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.Lead", b =>
                {
                    b.Navigation("LogsIntegracao");

                    b.Navigation("Origem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
