// <auto-generated />
using System;
using LeadEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeadEngineDbContext))]
    [Migration("20260722224938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LeadEngine.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CnpjNormalizado")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<bool>("ConsentimentoContato")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ConsentimentoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("EmailNormalizado")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErroEnvio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("HospitalDesejado")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("IdadesJson")
                        .HasColumnType("json");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("OperadoraDesejada")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("PlanoAtual")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool?>("PossuiPlanoAtual")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("QuantidadeFuncionarios")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeVidas")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TextoConsentimentoVersao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int?>("UltimoStatusHttpIntegracao")
                        .HasColumnType("int");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("WhatsAppNormalizado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.HasIndex("WhatsAppNormalizado");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.LogIntegracaoLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("StatusHttp")
                        .HasColumnType("int");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("LeadId");

                    b.ToTable("LogsIntegracaoLead", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.OrigemLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdGroupId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("AdId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CampaignId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Device")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Gbraid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Gclid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Keyword")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("LandingPage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MatchType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Wbraid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("Gclid");

                    b.HasIndex("LandingPage");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.HasIndex("UtmCampaign");

                    b.ToTable("OrigensLead", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.TentativaCapturaLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Duplicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gclid")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("LandingPage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("WhatsAppNormalizado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("LeadId");

                    b.HasIndex("WhatsAppNormalizado");

                    b.ToTable("TentativasCapturaLead", (string)null);
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.LogIntegracaoLead", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Lead", "Lead")
                        .WithMany("LogsIntegracao")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.OrigemLead", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Lead", "Lead")
                        .WithOne("Origem")
                        .HasForeignKey("LeadEngine.Domain.Entities.OrigemLead", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.TentativaCapturaLead", b =>
                {
                    b.HasOne("LeadEngine.Domain.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadEngine.Domain.Entities.Lead", b =>
                {
                    b.Navigation("LogsIntegracao");

                    b.Navigation("Origem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
